services:
  web:
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:80"
    volumes:
      - ./woori-ib-portal:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
